[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#87CEFA"

# Color used for almost all text.
textColor = "#00008B"